### PR TITLE
Add Skills section.

### PR DESCRIPTION
**Pull request by bibiebliss**

### CODE REVIEW

**Comment by logannc** [comment]
Go ahead and take screenshots of the these UI changes (typically with a before/after)

**Comment by bibiebliss** [comment]
so there's no before because it's a new section but this is how it looks:

image

**Comment by bibiebliss** [comment]
BEFORE:
Screen Shot 2021-06-04 at 4 07 35 PM
Screen Shot 2021-06-04 at 4 08 16 PM

AFTER:
Screen Shot 2021-06-04 at 4 22 16 PM
Screen Shot 2021-06-04 at 4 08 28 PM

**Comment by logannc** [comment]
Love it! Consider adding a black border on the text so that it is visible on the backgrounds you've chosen.

**Review by logannc — APPROVED** [review]

**Pull request merged**
